import Foundation

/// Frozen, stable display names for every palette, keyed by palette id.
///
/// Generated once from `PaletteNaming` and committed so names never drift if the
/// naming algorithm changes. Regenerate only intentionally. Duplicate base names are
/// disambiguated with a trailing ordinal in id order.
enum PaletteNames {
    static let byID: [String: String] = [
        "powerful-monochromatic-1": "Fierce Flame",
        "powerful-monochromatic-2": "Bold Ember",
        "powerful-monochromatic-3": "Roaring Garnet",
        "powerful-monochromatic-4": "Mighty Vermilion",
        "powerful-primary-1": "Roaring Tide",
        "powerful-primary-2": "Roaring Marine",
        "powerful-primary-3": "Roaring Harbor",
        "powerful-primary-4": "Bold Indigo",
        "powerful-analogous-1": "Fierce Amethyst",
        "powerful-analogous-2": "Fierce Iris",
        "powerful-analogous-3": "Fierce Ruby",
        "powerful-analogous-4": "Roaring Scarlet",
        "powerful-analogous-5": "Bold Amethyst",
        "powerful-analogous-6": "Mighty Orchid",
        "powerful-analogous-7": "Mighty Flame",
        "powerful-analogous-8": "Roaring Garnet 2",
        "powerful-analogous-9": "Bold Cinder",
        "powerful-analogous-10": "Fierce Garnet",
        "powerful-analogous-11": "Bold Daffodil",
        "powerful-analogous-12": "Fierce Garnet 2",
        "powerful-splitcomplementary-1": "Mighty Jade",
        "powerful-splitcomplementary-2": "Roaring Verdant",
        "powerful-splitcomplementary-3": "Roaring Garnet 3",
        "powerful-splitcomplementary-4": "Fierce Ember",
        "powerful-splitcomplementary-5": "Fierce Crimson",
        "powerful-splitcomplementary-6": "Fierce Clover",
        "powerful-splitcomplementary-7": "Bold Vermilion",
        "powerful-splitcomplementary-8": "Mighty Basil",
        "powerful-splitcomplementary-9": "Bold Verdant",
        "powerful-splitcomplementary-10": "Mighty Scarlet",
        "powerful-splitcomplementary-11": "Fierce Moss",
        "powerful-splitcomplementary-12": "Roaring Verdant 2",
        "powerful-neutral-1": "Bold Garnet",
        "powerful-neutral-2": "Mighty Garnet",
        "powerful-neutral-3": "Mighty Garnet 2",
        "powerful-neutral-4": "Bold Vermilion 2",
        "rich-monochromatic-1": "Deep Ember",
        "rich-monochromatic-2": "Lavish Cinder",
        "rich-monochromatic-3": "Opulent Flame",
        "rich-monochromatic-4": "Velvet Ember",
        "rich-primary-1": "Lavish Gilt",
        "rich-primary-2": "Deep Daffodil",
        "rich-primary-3": "Lavish Daffodil",
        "rich-primary-4": "Velvet Honey",
        "rich-analogous-1": "Deep Violet",
        "rich-analogous-2": "Lavish Violet",
        "rich-analogous-3": "Velvet Mauve",
        "rich-analogous-4": "Lavish Mauve",
        "rich-analogous-5": "Lavish Violet 2",
        "rich-analogous-6": "Deep Orchid",
        "rich-analogous-7": "Velvet Ruby",
        "rich-analogous-8": "Deep Ruby",
        "rich-analogous-9": "Velvet Crimson",
        "rich-analogous-10": "Opulent Ember",
        "rich-analogous-11": "Deep Cinder",
        "rich-analogous-12": "Deep Vermilion",
        "rich-splitcomplementary-1": "Velvet Pine",
        "rich-splitcomplementary-2": "Opulent Verdant",
        "rich-splitcomplementary-3": "Deep Scarlet",
        "rich-splitcomplementary-4": "Opulent Cinder",
        "rich-splitcomplementary-5": "Opulent Flame 2",
        "rich-splitcomplementary-6": "Opulent Verdant 2",
        "rich-splitcomplementary-7": "Lavish Moss",
        "rich-splitcomplementary-8": "Lavish Crimson",
        "rich-splitcomplementary-9": "Velvet Crimson 2",
        "rich-splitcomplementary-10": "Velvet Scarlet",
        "rich-splitcomplementary-11": "Velvet Garnet",
        "rich-splitcomplementary-12": "Lavish Cinder 2",
        "rich-neutral-1": "Opulent Vermilion",
        "rich-neutral-2": "Opulent Cinder 2",
        "rich-neutral-3": "Deep Vermilion 2",
        "rich-neutral-4": "Lavish Ruby",
        "romantic-monochromatic-1": "Tender Crimson",
        "romantic-monochromatic-2": "Dreaming Flame",
        "romantic-monochromatic-3": "Dreaming Cinder",
        "romantic-monochromatic-4": "Wistful Vermilion",
        "romantic-primary-1": "Dreaming Copper",
        "romantic-primary-2": "Dreaming Indigo",
        "romantic-primary-3": "Sweet Cobalt",
        "romantic-primary-4": "Dreaming Indigo 2",
        "romantic-analogous-1": "Dreaming Quartz",
        "romantic-analogous-2": "Wistful Peony",
        "romantic-analogous-3": "Sweet Peony",
        "romantic-analogous-4": "Wistful Sienna",
        "romantic-analogous-5": "Wistful Sienna 2",
        "romantic-analogous-6": "Dreaming Persimmon",
        "romantic-analogous-7": "Tender Thistle",
        "romantic-analogous-8": "Dreaming Marigold",
        "romantic-analogous-9": "Tender Persimmon",
        "romantic-analogous-10": "Tender Tangerine",
        "romantic-analogous-11": "Dreaming Buttercup",
        "romantic-analogous-12": "Sweet Scarlet",
        "romantic-splitcomplementary-1": "Sweet Persimmon",
        "romantic-splitcomplementary-2": "Wistful Basil",
        "romantic-splitcomplementary-3": "Tender Sienna",
        "romantic-splitcomplementary-4": "Wistful Scarlet",
        "romantic-splitcomplementary-5": "Tender Pine",
        "romantic-splitcomplementary-6": "Dreaming Verdant",
        "romantic-splitcomplementary-7": "Sweet Basil",
        "romantic-splitcomplementary-8": "Dreaming Clover",
        "romantic-splitcomplementary-9": "Dreaming Fern",
        "romantic-splitcomplementary-10": "Tender Persimmon 2",
        "romantic-splitcomplementary-11": "Tender Jade",
        "romantic-splitcomplementary-12": "Wistful Moss",
        "romantic-neutral-1": "Dreaming Peony",
        "romantic-neutral-2": "Wistful Amber",
        "romantic-neutral-3": "Sweet Sienna",
        "romantic-neutral-4": "Wistful Amber 2",
        "vital-monochromatic-1": "Bright Ruby",
        "vital-monochromatic-2": "Living Ember",
        "vital-monochromatic-3": "Pulsing Garnet",
        "vital-monochromatic-4": "Vivid Ruby",
        "vital-tertiary-1": "Pulsing Tide",
        "vital-tertiary-2": "Vivid Azure",
        "vital-tertiary-3": "Pulsing Harbor",
        "vital-tertiary-4": "Vivid Pine",
        "vital-analogous-1": "Vivid Amethyst",
        "vital-analogous-2": "Living Violet",
        "vital-analogous-3": "Bright Cinder",
        "vital-analogous-4": "Living Cinder",
        "vital-analogous-5": "Vivid Cinder",
        "vital-analogous-6": "Pulsing Crimson",
        "vital-analogous-7": "Vivid Lemon",
        "vital-analogous-8": "Vivid Cinder 2",
        "vital-analogous-9": "Living Citrine",
        "vital-analogous-10": "Living Gilt",
        "vital-analogous-11": "Vivid Sunlit",
        "vital-analogous-12": "Pulsing Cocoa",
        "vital-splitcomplementary-1": "Vivid Jade",
        "vital-splitcomplementary-2": "Bright Jade",
        "vital-splitcomplementary-3": "Living Crimson",
        "vital-splitcomplementary-4": "Living Azure",
        "vital-splitcomplementary-5": "Living Azure 2",
        "vital-splitcomplementary-6": "Pulsing Moss",
        "vital-splitcomplementary-7": "Pulsing Azure",
        "vital-splitcomplementary-8": "Bright Azure",
        "vital-splitcomplementary-9": "Pulsing Marine",
        "vital-splitcomplementary-10": "Bright Garnet",
        "vital-splitcomplementary-11": "Living Marine",
        "vital-splitcomplementary-12": "Vivid Scarlet",
        "vital-neutral-1": "Pulsing Garnet 2",
        "vital-neutral-2": "Pulsing Scarlet",
        "vital-neutral-3": "Living Garnet",
        "vital-neutral-4": "Bright Ember",
        "earthy-monochromatic-1": "Wild Ruby",
        "earthy-monochromatic-2": "Rustic Ruby",
        "earthy-monochromatic-3": "Wild Cinder",
        "earthy-monochromatic-4": "Raw Flame",
        "earthy-tertiary-1": "Rustic Marine",
        "earthy-tertiary-2": "Rustic Cobalt",
        "earthy-tertiary-3": "Raw Verdant",
        "earthy-tertiary-4": "Rooted Clover",
        "earthy-analogous-1": "Raw Iris",
        "earthy-analogous-2": "Wild Orchid",
        "earthy-analogous-3": "Rustic Plum",
        "earthy-analogous-4": "Raw Wisteria",
        "earthy-analogous-5": "Raw Garnet",
        "earthy-analogous-6": "Rooted Cinder",
        "earthy-analogous-7": "Wild Garnet",
        "earthy-analogous-8": "Wild Flame",
        "earthy-analogous-9": "Rustic Honey",
        "earthy-analogous-10": "Wild Chestnut",
        "earthy-analogous-11": "Rooted Hazel",
        "earthy-analogous-12": "Rooted Loam",
        "earthy-splitcomplementary-1": "Raw Moss",
        "earthy-splitcomplementary-2": "Raw Pine",
        "earthy-splitcomplementary-3": "Wild Moss",
        "earthy-splitcomplementary-4": "Raw Clover",
        "earthy-splitcomplementary-5": "Wild Pine",
        "earthy-splitcomplementary-6": "Raw Verdant 2",
        "earthy-splitcomplementary-7": "Rustic Fern",
        "earthy-splitcomplementary-8": "Wild Fern",
        "earthy-splitcomplementary-9": "Rustic Meadow",
        "earthy-splitcomplementary-10": "Rooted Jade",
        "earthy-splitcomplementary-11": "Raw Harbor",
        "earthy-splitcomplementary-12": "Rooted Basil",
        "earthy-neutral-1": "Rooted Ruby",
        "earthy-neutral-2": "Rustic Flame",
        "earthy-neutral-3": "Raw Vermilion",
        "earthy-neutral-4": "Rooted Crimson",
        "friendly-monochromatic-1": "Sunny Walnut",
        "friendly-monochromatic-2": "Sunny Walnut 2",
        "friendly-monochromatic-3": "Sunny Chestnut",
        "friendly-monochromatic-4": "Cheerful Loam",
        "friendly-secondary-1": "Sunny Amethyst",
        "friendly-secondary-2": "Easy Iris",
        "friendly-secondary-3": "Cheerful Lemon",
        "friendly-secondary-4": "Cheerful Thistle",
        "friendly-analogous-1": "Warm Cinder",
        "friendly-analogous-2": "Easy Garnet",
        "friendly-analogous-3": "Easy Sunlit",
        "friendly-analogous-4": "Sunny Walnut 3",
        "friendly-analogous-5": "Cheerful Sunlit",
        "friendly-analogous-6": "Sunny Umber",
        "friendly-analogous-7": "Sunny Umber 2",
        "friendly-analogous-8": "Warm Walnut",
        "friendly-analogous-9": "Easy Citrine",
        "friendly-analogous-10": "Easy Chestnut",
        "friendly-analogous-11": "Cheerful Daffodil",
        "friendly-analogous-12": "Sunny Umber 3",
        "friendly-splitcomplementary-1": "Easy Tide",
        "friendly-splitcomplementary-2": "Sunny Tide",
        "friendly-splitcomplementary-3": "Warm Honey",
        "friendly-splitcomplementary-4": "Easy Umber",
        "friendly-splitcomplementary-5": "Sunny Chestnut 2",
        "friendly-splitcomplementary-6": "Easy Pine",
        "friendly-splitcomplementary-7": "Warm Chestnut",
        "friendly-splitcomplementary-8": "Sunny Harbor",
        "friendly-splitcomplementary-9": "Easy Jade",
        "friendly-splitcomplementary-10": "Easy Sunlit 2",
        "friendly-splitcomplementary-11": "Easy Moss",
        "friendly-splitcomplementary-12": "Sunny Buttercup",
        "friendly-neutral-1": "Cheerful Daffodil 2",
        "friendly-neutral-2": "Warm Sunlit",
        "friendly-neutral-3": "Easy Daffodil",
        "friendly-neutral-4": "Cheerful Chamomile",
        "soft-monochromatic-1": "Gentle Walnut",
        "soft-monochromatic-2": "Hushed Clay",
        "soft-monochromatic-3": "Gentle Cocoa",
        "soft-monochromatic-4": "Tender Cocoa",
        "soft-secondary-1": "Downy Quartz",
        "soft-secondary-2": "Downy Verdant",
        "soft-secondary-3": "Gentle Peony",
        "soft-secondary-4": "Gentle Wisteria",
        "soft-analogous-1": "Hushed Persimmon",
        "soft-analogous-2": "Downy Buttercup",
        "soft-analogous-3": "Downy Gilt",
        "soft-analogous-4": "Gentle Amber",
        "soft-analogous-5": "Downy Lemon",
        "soft-analogous-6": "Gentle Citrine",
        "soft-analogous-7": "Tender Chamomile",
        "soft-analogous-8": "Hushed Daffodil",
        "soft-analogous-9": "Tender Lemon",
        "soft-analogous-10": "Downy Gilt 2",
        "soft-analogous-11": "Gentle Honey",
        "soft-analogous-12": "Tender Clay",
        "soft-splitcomplementary-1": "Hushed Harbor",
        "soft-splitcomplementary-2": "Downy Clover",
        "soft-splitcomplementary-3": "Gentle Honey 2",
        "soft-splitcomplementary-4": "Downy Slate",
        "soft-splitcomplementary-5": "Downy Basil",
        "soft-splitcomplementary-6": "Gentle Tide",
        "soft-splitcomplementary-7": "Hushed Moss",
        "soft-splitcomplementary-8": "Downy Basil 2",
        "soft-splitcomplementary-9": "Hushed Pine",
        "soft-splitcomplementary-10": "Hushed Harbor 2",
        "soft-splitcomplementary-11": "Downy Verdant 2",
        "soft-splitcomplementary-12": "Hushed Slate",
        "soft-neutral-1": "Downy Buttercup 2",
        "soft-neutral-2": "Tender Gilt",
        "soft-neutral-3": "Hushed Honey",
        "soft-neutral-4": "Hushed Chamomile",
        "welcoming-monochromatic-1": "Cozy Walnut",
        "welcoming-monochromatic-2": "Glowing Bark",
        "welcoming-monochromatic-3": "Inviting Chestnut",
        "welcoming-monochromatic-4": "Glowing Umber",
        "welcoming-tertiary-1": "Open Amethyst",
        "welcoming-tertiary-2": "Inviting Iris",
        "welcoming-tertiary-3": "Open Quartz",
        "welcoming-tertiary-4": "Open Cocoa",
        "welcoming-analogous-1": "Cozy Daffodil",
        "welcoming-analogous-2": "Glowing Daffodil",
        "welcoming-analogous-3": "Inviting Citrine",
        "welcoming-analogous-4": "Cozy Hazel",
        "welcoming-analogous-5": "Open Citrine",
        "welcoming-analogous-6": "Open Clay",
        "welcoming-analogous-7": "Cozy Buttercup",
        "welcoming-analogous-8": "Open Clay 2",
        "welcoming-analogous-9": "Cozy Citrine",
        "welcoming-analogous-10": "Glowing Umber 2",
        "welcoming-analogous-11": "Cozy Verdant",
        "welcoming-analogous-12": "Cozy Sunlit",
        "welcoming-splitcomplementary-1": "Inviting Tide",
        "welcoming-splitcomplementary-2": "Cozy Indigo",
        "welcoming-splitcomplementary-3": "Open Gilt",
        "welcoming-splitcomplementary-4": "Glowing Bark 2",
        "welcoming-splitcomplementary-5": "Open Chestnut",
        "welcoming-splitcomplementary-6": "Open Orchid",
        "welcoming-splitcomplementary-7": "Inviting Umber",
        "welcoming-splitcomplementary-8": "Glowing Azure",
        "welcoming-splitcomplementary-9": "Inviting Iris 2",
        "welcoming-splitcomplementary-10": "Glowing Citrine",
        "welcoming-splitcomplementary-11": "Open Chestnut 2",
        "welcoming-splitcomplementary-12": "Cozy Buttercup 2",
        "welcoming-neutral-1": "Glowing Daffodil 2",
        "welcoming-neutral-2": "Cozy Sunlit 2",
        "welcoming-neutral-3": "Glowing Daffodil 3",
        "welcoming-neutral-4": "Glowing Chamomile",
        "moving-monochromatic-1": "Drifting Citrine",
        "moving-monochromatic-2": "Surging Daffodil",
        "moving-monochromatic-3": "Restless Buttercup",
        "moving-monochromatic-4": "Flowing Lemon",
        "moving-primary-1": "Flowing Ruby",
        "moving-primary-2": "Surging Garnet",
        "moving-primary-3": "Surging Persimmon",
        "moving-primary-4": "Surging Cobalt",
        "moving-analogous-1": "Flowing Citrine",
        "moving-analogous-2": "Surging Sunlit",
        "moving-analogous-3": "Flowing Sunlit",
        "moving-analogous-4": "Flowing Loam",
        "moving-analogous-5": "Drifting Citrine 2",
        "moving-analogous-6": "Flowing Sunlit 2",
        "moving-analogous-7": "Drifting Jade",
        "moving-analogous-8": "Drifting Sunlit",
        "moving-analogous-9": "Restless Citrine",
        "moving-analogous-10": "Surging Daffodil 2",
        "moving-analogous-11": "Drifting Clover",
        "moving-analogous-12": "Flowing Pine",
        "moving-splitcomplementary-1": "Drifting Tide",
        "moving-splitcomplementary-2": "Drifting Indigo",
        "moving-splitcomplementary-3": "Drifting Honey",
        "moving-splitcomplementary-4": "Surging Lemon",
        "moving-splitcomplementary-5": "Restless Daffodil",
        "moving-splitcomplementary-6": "Flowing Amethyst",
        "moving-splitcomplementary-7": "Surging Indigo",
        "moving-splitcomplementary-8": "Flowing Cobalt",
        "moving-splitcomplementary-9": "Surging Mauve",
        "moving-splitcomplementary-10": "Surging Citrine",
        "moving-splitcomplementary-11": "Restless Violet",
        "moving-splitcomplementary-12": "Restless Peony",
        "moving-neutral-1": "Flowing Daffodil",
        "moving-neutral-2": "Surging Chamomile",
        "moving-neutral-3": "Surging Daffodil 3",
        "moving-neutral-4": "Drifting Chamomile",
        "elegant-monochromatic-1": "Refined Daffodil",
        "elegant-monochromatic-2": "Refined Citrine",
        "elegant-monochromatic-3": "Graceful Sunlit",
        "elegant-monochromatic-4": "Polished Citrine",
        "elegant-primary-1": "Graceful Slate",
        "elegant-primary-2": "Stately Harbor",
        "elegant-primary-3": "Polished Cobalt",
        "elegant-primary-4": "Polished Honey",
        "elegant-analogous-1": "Refined Chamomile",
        "elegant-analogous-2": "Stately Buttercup",
        "elegant-analogous-3": "Polished Gilt",
        "elegant-analogous-4": "Graceful Gilt",
        "elegant-analogous-5": "Stately Basil",
        "elegant-analogous-6": "Polished Buttercup",
        "elegant-analogous-7": "Graceful Meadow",
        "elegant-analogous-8": "Refined Daffodil 2",
        "elegant-analogous-9": "Polished Meadow",
        "elegant-analogous-10": "Graceful Citrine",
        "elegant-analogous-11": "Refined Fern",
        "elegant-analogous-12": "Stately Pine",
        "elegant-splitcomplementary-1": "Stately Slate",
        "elegant-splitcomplementary-2": "Polished Amethyst",
        "elegant-splitcomplementary-3": "Graceful Azure",
        "elegant-splitcomplementary-4": "Refined Honey",
        "elegant-splitcomplementary-5": "Polished Harbor",
        "elegant-splitcomplementary-6": "Graceful Quartz",
        "elegant-splitcomplementary-7": "Polished Azure",
        "elegant-splitcomplementary-8": "Refined Honey 2",
        "elegant-splitcomplementary-9": "Graceful Indigo",
        "elegant-splitcomplementary-10": "Graceful Slate 2",
        "elegant-splitcomplementary-11": "Graceful Wisteria",
        "elegant-splitcomplementary-12": "Refined Rose",
        "elegant-neutral-1": "Graceful Gilt 2",
        "elegant-neutral-2": "Refined Daffodil 3",
        "elegant-neutral-3": "Stately Sunlit",
        "elegant-neutral-4": "Polished Lemon",
        "trendy-monochromatic-1": "Bright Fern",
        "trendy-monochromatic-2": "Bright Moss",
        "trendy-monochromatic-3": "Electric Basil",
        "trendy-monochromatic-4": "Bright Fern 2",
        "trendy-tertiary-1": "Sharp Tide",
        "trendy-tertiary-2": "Sharp Sapphire",
        "trendy-tertiary-3": "Bright Harbor",
        "trendy-tertiary-4": "Electric Moss",
        "trendy-analogous-1": "Sharp Citrine",
        "trendy-analogous-2": "Electric Honey",
        "trendy-analogous-3": "Electric Bark",
        "trendy-analogous-4": "Modern Umber",
        "trendy-analogous-5": "Bright Citrine",
        "trendy-analogous-6": "Sharp Sunlit",
        "trendy-analogous-7": "Sharp Jade",
        "trendy-analogous-8": "Sharp Verdant",
        "trendy-analogous-9": "Electric Jade",
        "trendy-analogous-10": "Bright Fern 3",
        "trendy-analogous-11": "Modern Moss",
        "trendy-analogous-12": "Modern Pine",
        "trendy-splitcomplementary-1": "Electric Amethyst",
        "trendy-splitcomplementary-2": "Sharp Amethyst",
        "trendy-splitcomplementary-3": "Modern Pine 2",
        "trendy-splitcomplementary-4": "Modern Pine 3",
        "trendy-splitcomplementary-5": "Electric Verdant",
        "trendy-splitcomplementary-6": "Electric Crimson",
        "trendy-splitcomplementary-7": "Modern Meadow",
        "trendy-splitcomplementary-8": "Modern Iris",
        "trendy-splitcomplementary-9": "Electric Garnet",
        "trendy-splitcomplementary-10": "Modern Jade",
        "trendy-splitcomplementary-11": "Electric Garnet 2",
        "trendy-splitcomplementary-12": "Sharp Clover",
        "trendy-neutral-1": "Electric Moss 2",
        "trendy-neutral-2": "Electric Meadow",
        "trendy-neutral-3": "Sharp Moss",
        "trendy-neutral-4": "Electric Verdant 2",
        "fresh-monochromatic-1": "Cool Fern",
        "fresh-monochromatic-2": "Crisp Fern",
        "fresh-monochromatic-3": "Crisp Moss",
        "fresh-monochromatic-4": "Cool Meadow",
        "fresh-secondary-1": "Crisp Citrine",
        "fresh-secondary-2": "Crisp Chestnut",
        "fresh-secondary-3": "Dewy Mauve",
        "fresh-secondary-4": "Dewy Jade",
        "fresh-analogous-1": "Crisp Citrine 2",
        "fresh-analogous-2": "Dewy Sunlit",
        "fresh-analogous-3": "Clean Clover",
        "fresh-analogous-4": "Dewy Jade 2",
        "fresh-analogous-5": "Clean Jade",
        "fresh-analogous-6": "Crisp Moss 2",
        "fresh-analogous-7": "Cool Basil",
        "fresh-analogous-8": "Dewy Moss",
        "fresh-analogous-9": "Cool Jade",
        "fresh-analogous-10": "Dewy Pine",
        "fresh-analogous-11": "Dewy Tide",
        "fresh-analogous-12": "Dewy Verdant",
        "fresh-splitcomplementary-1": "Cool Amethyst",
        "fresh-splitcomplementary-2": "Dewy Mauve 2",
        "fresh-splitcomplementary-3": "Dewy Moss 2",
        "fresh-splitcomplementary-4": "Crisp Fern 2",
        "fresh-splitcomplementary-5": "Crisp Jade",
        "fresh-splitcomplementary-6": "Dewy Scarlet",
        "fresh-splitcomplementary-7": "Cool Pine",
        "fresh-splitcomplementary-8": "Cool Plum",
        "fresh-splitcomplementary-9": "Crisp Mauve",
        "fresh-splitcomplementary-10": "Clean Jade 2",
        "fresh-splitcomplementary-11": "Clean Crimson",
        "fresh-splitcomplementary-12": "Dewy Jade 3",
        "fresh-neutral-1": "Crisp Moss 3",
        "fresh-neutral-2": "Cool Meadow 2",
        "fresh-neutral-3": "Clean Moss",
        "fresh-neutral-4": "Clean Meadow",
        "traditional-monochromatic-1": "Classic Basil",
        "traditional-monochromatic-2": "Heritage Verdant",
        "traditional-monochromatic-3": "Timeless Verdant",
        "traditional-monochromatic-4": "Heritage Meadow",
        "traditional-secondary-1": "Timeless Pine",
        "traditional-secondary-2": "Heritage Basil",
        "traditional-secondary-3": "Classic Pine",
        "traditional-secondary-4": "Heritage Basil 2",
        "traditional-analogous-1": "Classic Honey",
        "traditional-analogous-2": "Heritage Honey",
        "traditional-analogous-3": "Old-World Clover",
        "traditional-analogous-4": "Old-World Sunlit",
        "traditional-analogous-5": "Timeless Pine 2",
        "traditional-analogous-6": "Classic Moss",
        "traditional-analogous-7": "Timeless Fern",
        "traditional-analogous-8": "Heritage Clover",
        "traditional-analogous-9": "Heritage Pine",
        "traditional-analogous-10": "Old-World Moss",
        "traditional-analogous-11": "Timeless Fern 2",
        "traditional-analogous-12": "Classic Verdant",
        "traditional-splitcomplementary-1": "Timeless Pine 3",
        "traditional-splitcomplementary-2": "Classic Moss 2",
        "traditional-splitcomplementary-3": "Old-World Meadow",
        "traditional-splitcomplementary-4": "Heritage Clover 2",
        "traditional-splitcomplementary-5": "Timeless Verdant 2",
        "traditional-splitcomplementary-6": "Old-World Pine",
        "traditional-splitcomplementary-7": "Timeless Basil",
        "traditional-splitcomplementary-8": "Classic Verdant 2",
        "traditional-splitcomplementary-9": "Heritage Iris",
        "traditional-splitcomplementary-10": "Old-World Amethyst",
        "traditional-splitcomplementary-11": "Timeless Thistle",
        "traditional-splitcomplementary-12": "Classic Verdant 3",
        "traditional-neutral-1": "Classic Meadow",
        "traditional-neutral-2": "Timeless Moss",
        "traditional-neutral-3": "Classic Meadow 2",
        "traditional-neutral-4": "Timeless Fern 3",
        "refreshing-monochromatic-1": "Sparkling Moss",
        "refreshing-monochromatic-2": "Cooling Pine",
        "refreshing-monochromatic-3": "Clear Clover",
        "refreshing-monochromatic-4": "Clear Fern",
        "refreshing-tertiary-1": "Sparkling Jade",
        "refreshing-tertiary-2": "Cooling Verdant",
        "refreshing-tertiary-3": "Cooling Clover",
        "refreshing-tertiary-4": "Cooling Loam",
        "refreshing-analogous-1": "Clear Jade",
        "refreshing-analogous-2": "Clear Verdant",
        "refreshing-analogous-3": "Breezy Verdant",
        "refreshing-analogous-4": "Sparkling Jade 2",
        "refreshing-analogous-5": "Sparkling Jade 3",
        "refreshing-analogous-6": "Sparkling Verdant",
        "refreshing-analogous-7": "Breezy Fern",
        "refreshing-analogous-8": "Cooling Fern",
        "refreshing-analogous-9": "Breezy Jade",
        "refreshing-analogous-10": "Cooling Pine 2",
        "refreshing-analogous-11": "Breezy Basil",
        "refreshing-analogous-12": "Clear Marine",
        "refreshing-splitcomplementary-1": "Breezy Cinder",
        "refreshing-splitcomplementary-2": "Breezy Scarlet",
        "refreshing-splitcomplementary-3": "Clear Meadow",
        "refreshing-splitcomplementary-4": "Clear Meadow 2",
        "refreshing-splitcomplementary-5": "Sparkling Basil",
        "refreshing-splitcomplementary-6": "Sparkling Crimson",
        "refreshing-splitcomplementary-7": "Sparkling Clay",
        "refreshing-splitcomplementary-8": "Breezy Sienna",
        "refreshing-splitcomplementary-9": "Cooling Buttercup",
        "refreshing-splitcomplementary-10": "Clear Clover 2",
        "refreshing-splitcomplementary-11": "Clear Vermilion",
        "refreshing-splitcomplementary-12": "Clear Walnut",
        "refreshing-neutral-1": "Breezy Moss",
        "refreshing-neutral-2": "Sparkling Verdant 2",
        "refreshing-neutral-3": "Sparkling Moss 2",
        "refreshing-neutral-4": "Breezy Meadow",
        "tropical-monochromatic-1": "Sunlit Pine",
        "tropical-monochromatic-2": "Island Verdant",
        "tropical-monochromatic-3": "Island Meadow",
        "tropical-monochromatic-4": "Lush Jade",
        "tropical-tertiary-1": "Island Basil",
        "tropical-tertiary-2": "Sunlit Gilt",
        "tropical-tertiary-3": "Vivid Meadow",
        "tropical-tertiary-4": "Sunlit Meadow",
        "tropical-analogous-1": "Vivid Basil",
        "tropical-analogous-2": "Island Jade",
        "tropical-analogous-3": "Island Pine",
        "tropical-analogous-4": "Sunlit Fern",
        "tropical-analogous-5": "Island Harbor",
        "tropical-analogous-6": "Lush Sapphire",
        "tropical-analogous-7": "Lush Pine",
        "tropical-analogous-8": "Vivid Pine 2",
        "tropical-analogous-9": "Sunlit Harbor",
        "tropical-analogous-10": "Sunlit Clover",
        "tropical-analogous-11": "Sunlit Cobalt",
        "tropical-analogous-12": "Lush Azure",
        "tropical-splitcomplementary-1": "Lush Persimmon",
        "tropical-splitcomplementary-2": "Sunlit Persimmon",
        "tropical-splitcomplementary-3": "Vivid Pine 3",
        "tropical-splitcomplementary-4": "Sunlit Chamomile",
        "tropical-splitcomplementary-5": "Island Buttercup",
        "tropical-splitcomplementary-6": "Lush Citrine",
        "tropical-splitcomplementary-7": "Sunlit Tangerine",
        "tropical-splitcomplementary-8": "Vivid Fern",
        "tropical-splitcomplementary-9": "Sunlit Persimmon 2",
        "tropical-splitcomplementary-10": "Lush Meadow",
        "tropical-splitcomplementary-11": "Sunlit Copper",
        "tropical-splitcomplementary-12": "Lush Daffodil",
        "tropical-neutral-1": "Lush Jade 2",
        "tropical-neutral-2": "Vivid Meadow 2",
        "tropical-neutral-3": "Sunlit Jade",
        "tropical-neutral-4": "Lush Fern",
        "classic-monochromatic-1": "Timeless Azure",
        "classic-monochromatic-2": "Noble Harbor",
        "classic-monochromatic-3": "Noble Sapphire",
        "classic-monochromatic-4": "Enduring Azure",
        "classic-primary-1": "Noble Cinder",
        "classic-primary-2": "Noble Garnet",
        "classic-primary-3": "Enduring Copper",
        "classic-primary-4": "Enduring Chamomile",
        "classic-analogous-1": "Noble Jade",
        "classic-analogous-2": "Noble Verdant",
        "classic-analogous-3": "Timeless Tide",
        "classic-analogous-4": "Enduring Azure 2",
        "classic-analogous-5": "Timeless Jade",
        "classic-analogous-6": "Timeless Verdant 3",
        "classic-analogous-7": "Enduring Tide",
        "classic-analogous-8": "Noble Cobalt",
        "classic-analogous-9": "Enduring Tide 2",
        "classic-analogous-10": "Poised Marine",
        "classic-analogous-11": "Enduring Mauve",
        "classic-analogous-12": "Timeless Tide 2",
        "classic-splitcomplementary-1": "Enduring Tide 3",
        "classic-splitcomplementary-2": "Noble Sapphire 2",
        "classic-splitcomplementary-3": "Poised Slate",
        "classic-splitcomplementary-4": "Enduring Cobalt",
        "classic-splitcomplementary-5": "Noble Marine",
        "classic-splitcomplementary-6": "Noble Scarlet",
        "classic-splitcomplementary-7": "Poised Azure",
        "classic-splitcomplementary-8": "Enduring Gilt",
        "classic-splitcomplementary-9": "Noble Sunlit",
        "classic-splitcomplementary-10": "Noble Tide",
        "classic-splitcomplementary-11": "Poised Clay",
        "classic-splitcomplementary-12": "Enduring Tide 4",
        "classic-neutral-1": "Noble Marine 2",
        "classic-neutral-2": "Noble Sapphire 3",
        "classic-neutral-3": "Enduring Marine",
        "classic-neutral-4": "Noble Slate",
        "dependable-monochromatic-1": "Solid Harbor",
        "dependable-monochromatic-2": "Solid Tide",
        "dependable-monochromatic-3": "Grounded Indigo",
        "dependable-monochromatic-4": "True Tide",
        "dependable-primary-1": "Steady Honey",
        "dependable-primary-2": "True Daffodil",
        "dependable-primary-3": "Steady Garnet",
        "dependable-primary-4": "True Sunlit",
        "dependable-analogous-1": "Steady Pine",
        "dependable-analogous-2": "True Fern",
        "dependable-analogous-3": "Solid Fern",
        "dependable-analogous-4": "Steady Meadow",
        "dependable-analogous-5": "Steady Clover",
        "dependable-analogous-6": "Grounded Pine",
        "dependable-analogous-7": "Solid Tide 2",
        "dependable-analogous-8": "Steady Tide",
        "dependable-analogous-9": "Steady Azure",
        "dependable-analogous-10": "Steady Slate",
        "dependable-analogous-11": "Solid Tide 3",
        "dependable-analogous-12": "Solid Harbor 2",
        "dependable-splitcomplementary-1": "Steady Sapphire",
        "dependable-splitcomplementary-2": "Grounded Marine",
        "dependable-splitcomplementary-3": "Solid Tide 4",
        "dependable-splitcomplementary-4": "Steady Azure 2",
        "dependable-splitcomplementary-5": "Solid Slate",
        "dependable-splitcomplementary-6": "True Indigo",
        "dependable-splitcomplementary-7": "Steady Tide 2",
        "dependable-splitcomplementary-8": "Steady Cobalt",
        "dependable-splitcomplementary-9": "Solid Walnut",
        "dependable-splitcomplementary-10": "True Hazel",
        "dependable-splitcomplementary-11": "True Tide 2",
        "dependable-splitcomplementary-12": "Steady Cobalt 2",
        "dependable-neutral-1": "Steady Marine",
        "dependable-neutral-2": "Solid Tide 5",
        "dependable-neutral-3": "Grounded Azure",
        "dependable-neutral-4": "Solid Tide 6",
        "calm-monochromatic-1": "Still Azure",
        "calm-monochromatic-2": "Tranquil Tide",
        "calm-monochromatic-3": "Serene Marine",
        "calm-monochromatic-4": "Still Sapphire",
        "calm-primary-1": "Quiet Persimmon",
        "calm-primary-2": "Still Indigo",
        "calm-primary-3": "Tranquil Slate",
        "calm-primary-4": "Serene Sienna",
        "calm-analogous-1": "Quiet Harbor",
        "calm-analogous-2": "Tranquil Clover",
        "calm-analogous-3": "Tranquil Slate 2",
        "calm-analogous-4": "Still Moss",
        "calm-analogous-5": "Serene Harbor",
        "calm-analogous-6": "Still Slate",
        "calm-analogous-7": "Still Basil",
        "calm-analogous-8": "Serene Cobalt",
        "calm-analogous-9": "Still Harbor",
        "calm-analogous-10": "Still Harbor 2",
        "calm-analogous-11": "Tranquil Azure",
        "calm-analogous-12": "Serene Indigo",
        "calm-splitcomplementary-1": "Quiet Harbor 2",
        "calm-splitcomplementary-2": "Serene Slate",
        "calm-splitcomplementary-3": "Quiet Cobalt",
        "calm-splitcomplementary-4": "Tranquil Citrine",
        "calm-splitcomplementary-5": "Serene Persimmon",
        "calm-splitcomplementary-6": "Tranquil Buttercup",
        "calm-splitcomplementary-7": "Quiet Persimmon 2",
        "calm-splitcomplementary-8": "Quiet Harbor 3",
        "calm-splitcomplementary-9": "Quiet Sunlit",
        "calm-splitcomplementary-10": "Quiet Slate",
        "calm-splitcomplementary-11": "Still Daffodil",
        "calm-splitcomplementary-12": "Tranquil Cinder",
        "calm-neutral-1": "Tranquil Indigo",
        "calm-neutral-2": "Serene Sapphire",
        "calm-neutral-3": "Still Marine",
        "calm-neutral-4": "Serene Cobalt 2",
        "regal-monochromatic-1": "Noble Azure",
        "regal-monochromatic-2": "Royal Cobalt",
        "regal-monochromatic-3": "Majestic Sapphire",
        "regal-monochromatic-4": "Noble Indigo",
        "regal-tertiary-1": "Majestic Jade",
        "regal-tertiary-2": "Noble Verdant 2",
        "regal-tertiary-3": "Majestic Flame",
        "regal-tertiary-4": "Majestic Slate",
        "regal-analogous-1": "Majestic Jade 2",
        "regal-analogous-2": "Majestic Verdant",
        "regal-analogous-3": "Crowned Tide",
        "regal-analogous-4": "Royal Sapphire",
        "regal-analogous-5": "Royal Tide",
        "regal-analogous-6": "Royal Marine",
        "regal-analogous-7": "Noble Orchid",
        "regal-analogous-8": "Royal Tide 2",
        "regal-analogous-9": "Crowned Tide 2",
        "regal-analogous-10": "Majestic Cobalt",
        "regal-analogous-11": "Royal Amethyst",
        "regal-analogous-12": "Noble Mauve",
        "regal-splitcomplementary-1": "Majestic Buttercup",
        "regal-splitcomplementary-2": "Royal Citrine",
        "regal-splitcomplementary-3": "Noble Slate 2",
        "regal-splitcomplementary-4": "Royal Azure",
        "regal-splitcomplementary-5": "Crowned Sapphire",
        "regal-splitcomplementary-6": "Noble Chestnut",
        "regal-splitcomplementary-7": "Majestic Cobalt 2",
        "regal-splitcomplementary-8": "Noble Lemon",
        "regal-splitcomplementary-9": "Noble Hazel",
        "regal-splitcomplementary-10": "Noble Tide 2",
        "regal-splitcomplementary-11": "Majestic Cocoa",
        "regal-splitcomplementary-12": "Crowned Sapphire 2",
        "regal-neutral-1": "Noble Marine 3",
        "regal-neutral-2": "Majestic Cobalt 3",
        "regal-neutral-3": "Crowned Slate",
        "regal-neutral-4": "Royal Indigo",
        "magical-monochromatic-1": "Mystic Thistle",
        "magical-monochromatic-2": "Mystic Plum",
        "magical-monochromatic-3": "Enchanted Mauve",
        "magical-monochromatic-4": "Spellbound Thistle",
        "magical-secondary-1": "Mystic Jade",
        "magical-secondary-2": "Mystic Fern",
        "magical-secondary-3": "Enchanted Jade",
        "magical-secondary-4": "Enchanted Violet",
        "magical-analogous-1": "Enchanted Tide",
        "magical-analogous-2": "Mystic Azure",
        "magical-analogous-3": "Spellbound Amethyst",
        "magical-analogous-4": "Enchanted Amethyst",
        "magical-analogous-5": "Dreaming Tide",
        "magical-analogous-6": "Enchanted Azure",
        "magical-analogous-7": "Spellbound Mauve",
        "magical-analogous-8": "Enchanted Iris",
        "magical-analogous-9": "Enchanted Amethyst 2",
        "magical-analogous-10": "Spellbound Violet",
        "magical-analogous-11": "Spellbound Scarlet",
        "magical-analogous-12": "Mystic Wisteria",
        "magical-splitcomplementary-1": "Dreaming Citrine",
        "magical-splitcomplementary-2": "Mystic Cocoa",
        "magical-splitcomplementary-3": "Spellbound Thistle 2",
        "magical-splitcomplementary-4": "Enchanted Wisteria",
        "magical-splitcomplementary-5": "Dreaming Violet",
        "magical-splitcomplementary-6": "Mystic Pine",
        "magical-splitcomplementary-7": "Enchanted Violet 2",
        "magical-splitcomplementary-8": "Spellbound Chamomile",
        "magical-splitcomplementary-9": "Dreaming Jade",
        "magical-splitcomplementary-10": "Spellbound Mauve 2",
        "magical-splitcomplementary-11": "Mystic Pine 2",
        "magical-splitcomplementary-12": "Dreaming Amethyst",
        "magical-neutral-1": "Enchanted Iris 2",
        "magical-neutral-2": "Mystic Plum 2",
        "magical-neutral-3": "Enchanted Wisteria 2",
        "magical-neutral-4": "Mystic Mauve",
        "nostalgic-monochromatic-1": "Faded Violet",
        "nostalgic-monochromatic-2": "Remembered Violet",
        "nostalgic-monochromatic-3": "Faded Amethyst",
        "nostalgic-monochromatic-4": "Faded Mauve",
        "nostalgic-secondary-1": "Remembered Quartz",
        "nostalgic-secondary-2": "Vintage Loam",
        "nostalgic-secondary-3": "Remembered Pine",
        "nostalgic-secondary-4": "Vintage Moss",
        "nostalgic-analogous-1": "Remembered Harbor",
        "nostalgic-analogous-2": "Vintage Tide",
        "nostalgic-analogous-3": "Remembered Azure",
        "nostalgic-analogous-4": "Faded Mauve 2",
        "nostalgic-analogous-5": "Vintage Harbor",
        "nostalgic-analogous-6": "Wistful Harbor",
        "nostalgic-analogous-7": "Faded Wisteria",
        "nostalgic-analogous-8": "Faded Indigo",
        "nostalgic-analogous-9": "Remembered Quartz 2",
        "nostalgic-analogous-10": "Remembered Thistle",
        "nostalgic-analogous-11": "Faded Sienna",
        "nostalgic-analogous-12": "Vintage Amber",
        "nostalgic-splitcomplementary-1": "Faded Quartz",
        "nostalgic-splitcomplementary-2": "Remembered Blush",
        "nostalgic-splitcomplementary-3": "Remembered Verdant",
        "nostalgic-splitcomplementary-4": "Wistful Cocoa",
        "nostalgic-splitcomplementary-5": "Faded Pine",
        "nostalgic-splitcomplementary-6": "Remembered Clover",
        "nostalgic-splitcomplementary-7": "Faded Basil",
        "nostalgic-splitcomplementary-8": "Remembered Fern",
        "nostalgic-splitcomplementary-9": "Faded Hazel",
        "nostalgic-splitcomplementary-10": "Wistful Orchid",
        "nostalgic-splitcomplementary-11": "Wistful Peony 2",
        "nostalgic-splitcomplementary-12": "Wistful Loam",
        "nostalgic-neutral-1": "Vintage Coral",
        "nostalgic-neutral-2": "Faded Petal",
        "nostalgic-neutral-3": "Vintage Blush",
        "nostalgic-neutral-4": "Vintage Iris",
        "energetic-monochromatic-1": "Lively Thistle",
        "energetic-monochromatic-2": "Kinetic Iris",
        "energetic-monochromatic-3": "Lively Orchid",
        "energetic-monochromatic-4": "Lively Plum",
        "energetic-tertiary-1": "Electric Citrine",
        "energetic-tertiary-2": "Lively Loam",
        "energetic-tertiary-3": "Lively Citrine",
        "energetic-tertiary-4": "Kinetic Plum",
        "energetic-analogous-1": "Lively Tide",
        "energetic-analogous-2": "Kinetic Sapphire",
        "energetic-analogous-3": "Kinetic Iris 2",
        "energetic-analogous-4": "Kinetic Orchid",
        "energetic-analogous-5": "Electric Amethyst 2",
        "energetic-analogous-6": "Electric Orchid",
        "energetic-analogous-7": "Kinetic Scarlet",
        "energetic-analogous-8": "Kinetic Iris 3",
        "energetic-analogous-9": "Charged Amethyst",
        "energetic-analogous-10": "Charged Plum",
        "energetic-analogous-11": "Charged Cinder",
        "energetic-analogous-12": "Electric Garnet 3",
        "energetic-splitcomplementary-1": "Charged Citrine",
        "energetic-splitcomplementary-2": "Electric Buttercup",
        "energetic-splitcomplementary-3": "Charged Iris",
        "energetic-splitcomplementary-4": "Charged Wisteria",
        "energetic-splitcomplementary-5": "Charged Violet",
        "energetic-splitcomplementary-6": "Kinetic Moss",
        "energetic-splitcomplementary-7": "Lively Wisteria",
        "energetic-splitcomplementary-8": "Lively Chamomile",
        "energetic-splitcomplementary-9": "Kinetic Moss 2",
        "energetic-splitcomplementary-10": "Kinetic Thistle",
        "energetic-splitcomplementary-11": "Lively Moss",
        "energetic-splitcomplementary-12": "Charged Amethyst 2",
        "energetic-neutral-1": "Lively Iris",
        "energetic-neutral-2": "Charged Mauve",
        "energetic-neutral-3": "Lively Wisteria 2",
        "energetic-neutral-4": "Lively Mauve",
        "subdued-monochromatic-1": "Muted Iris",
        "subdued-monochromatic-2": "Soft Amethyst",
        "subdued-monochromatic-3": "Dusky Plum",
        "subdued-monochromatic-4": "Hushed Peony",
        "subdued-tertiary-1": "Dusky Basil",
        "subdued-tertiary-2": "Muted Basil",
        "subdued-tertiary-3": "Muted Hazel",
        "subdued-tertiary-4": "Muted Basil 2",
        "subdued-analogous-1": "Dusky Harbor",
        "subdued-analogous-2": "Hushed Tide",
        "subdued-analogous-3": "Muted Iris 2",
        "subdued-analogous-4": "Dusky Sapphire",
        "subdued-analogous-5": "Soft Quartz",
        "subdued-analogous-6": "Soft Thistle",
        "subdued-analogous-7": "Dusky Persimmon",
        "subdued-analogous-8": "Soft Violet",
        "subdued-analogous-9": "Hushed Copper",
        "subdued-analogous-10": "Muted Mauve",
        "subdued-analogous-11": "Muted Amber",
        "subdued-analogous-12": "Soft Amber",
        "subdued-splitcomplementary-1": "Hushed Meadow",
        "subdued-splitcomplementary-2": "Soft Meadow",
        "subdued-splitcomplementary-3": "Hushed Blush",
        "subdued-splitcomplementary-4": "Dusky Wisteria",
        "subdued-splitcomplementary-5": "Dusky Basil 2",
        "subdued-splitcomplementary-6": "Dusky Sunlit",
        "subdued-splitcomplementary-7": "Muted Sunlit",
        "subdued-splitcomplementary-8": "Dusky Jade",
        "subdued-splitcomplementary-9": "Soft Chamomile",
        "subdued-splitcomplementary-10": "Dusky Meadow",
        "subdued-splitcomplementary-11": "Hushed Buttercup",
        "subdued-splitcomplementary-12": "Muted Fern",
        "subdued-neutral-1": "Hushed Camellia",
        "subdued-neutral-2": "Dusky Blush",
        "subdued-neutral-3": "Hushed Rose",
        "subdued-neutral-4": "Dusky Peony",
        "pure-mixed-1": "Simple Tangerine",
        "pure-mixed-2": "Clear Tangerine",
        "pure-mixed-3": "Clear Citrine",
        "pure-mixed-4": "Bright Citrine 2",
        "pure-mixed-5": "Bright Coral",
        "pure-mixed-6": "Clean Sunlit",
        "pure-mixed-7": "Clean Verdant",
        "pure-mixed-8": "Clear Sapphire",
        "pure-mixed-9": "Simple Coral",
        "pure-mixed-10": "Simple Verdant",
        "pure-mixed-11": "Clear Harbor",
        "pure-mixed-12": "Clear Sapphire 2",
        "pure-mixed-13": "Clear Sapphire 3",
        "pure-mixed-14": "Bright Coral 2",
        "pure-mixed-15": "Simple Moss",
        "pure-mixed-16": "Clean Moss 2",
        "pure-mixed-17": "Clean Sunlit 2",
        "pure-mixed-18": "Simple Honey",
        "pure-mixed-19": "Clean Sunlit 3",
        "pure-mixed-20": "Clean Honey",
        "pure-mixed-21": "Bright Sunlit",
        "pure-mixed-22": "Simple Moss 2",
        "pure-mixed-23": "Simple Jade",
        "pure-mixed-24": "Clean Buttercup",
        "pure-mixed-25": "Simple Verdant 2",
        "pure-mixed-26": "Clear Honey",
        "pure-mixed-27": "Clean Pine",
        "pure-mixed-28": "Bright Moss 2",
        "pure-mixed-29": "Bright Sunlit 2",
        "pure-mixed-30": "Bright Violet",
        "pure-mixed-31": "Clear Tide",
        "pure-mixed-32": "Clear Tide 2",
        "pure-mixed-33": "Clean Marine",
        "pure-mixed-34": "Bright Sapphire",
        "pure-mixed-35": "Clean Slate",
        "pure-mixed-36": "Clear Citrine 2",
        "pure-mixed-37": "Clean Coral",
        "pure-mixed-38": "Bright Sapphire 2",
        "pure-mixed-39": "Bright Amethyst",
        "pure-mixed-40": "Clear Camellia",
        "pure-mixed-41": "Clear Sapphire 4",
        "pure-mixed-42": "Simple Azure",
        "pure-mixed-43": "Clean Tide",
        "pure-mixed-44": "Bright Azure 2",
        "pure-mixed-45": "Clear Slate",
        "pure-mixed-46": "Clean Azure",
        "pure-mixed-47": "Clean Tide 2",
        "pure-mixed-48": "Clean Marine 2",
        "graphic-achromatic-1": "Striking Ash",
        "graphic-achromatic-2": "Striking Pewter",
        "graphic-achromatic-3": "Striking Pewter 2",
        "graphic-mixed-1": "Stark Ember",
        "graphic-mixed-2": "Bold Ember 2",
        "graphic-mixed-3": "Bold Umber",
        "graphic-mixed-4": "Vivid Umber",
        "graphic-mixed-5": "Vivid Lemon 2",
        "graphic-mixed-6": "Striking Basil",
        "graphic-mixed-7": "Striking Basil 2",
        "graphic-mixed-8": "Stark Basil",
        "graphic-mixed-9": "Bold Harbor",
        "graphic-mixed-10": "Bold Harbor 2",
        "graphic-mixed-11": "Vivid Thistle",
        "graphic-mixed-12": "Vivid Thistle 2",
        "graphic-mixed-13": "Stark Garnet",
        "graphic-mixed-14": "Bold Moss",
        "graphic-mixed-15": "Bold Daffodil 2",
        "graphic-mixed-16": "Vivid Daffodil",
        "graphic-mixed-17": "Vivid Daffodil 2",
        "graphic-mixed-18": "Striking Moss",
        "graphic-mixed-19": "Vivid Marine",
        "graphic-mixed-20": "Striking Moss 2",
        "graphic-mixed-21": "Vivid Daffodil 3",
        "graphic-mixed-22": "Stark Daffodil",
        "graphic-mixed-23": "Striking Daffodil",
        "graphic-mixed-24": "Bold Daffodil 3",
        "graphic-mixed-25": "Striking Daffodil 2",
        "graphic-mixed-26": "Bold Daffodil 4",
        "graphic-mixed-27": "Vivid Moss",
        "graphic-mixed-28": "Vivid Moss 2",
        "graphic-mixed-29": "Vivid Moss 3",
        "graphic-mixed-30": "Bold Moss 2",
        "graphic-mixed-31": "Striking Moss 3",
        "graphic-mixed-32": "Vivid Marine 2",
        "graphic-mixed-33": "Bold Marine",
        "graphic-mixed-34": "Stark Sapphire",
        "graphic-mixed-35": "Bold Orchid",
        "graphic-mixed-36": "Vivid Orchid",
        "graphic-mixed-37": "Bold Scarlet",
        "graphic-mixed-38": "Vivid Scarlet 2",
        "graphic-mixed-39": "Stark Sunlit",
        "graphic-mixed-40": "Bold Sunlit",
    ]
}
